### ISSUE TITLE
Logs Exploding with 502 errors

### ISSUE THREAD

**Issue by probably-not** [runsidekick/sidekick-agent-nodejs#12]
Starting in the last few days, my logs have exploded with the following error:

```
ERR! <CommunicationApiListener> An error occured on socket connection: Unexpected server response: 502 undefined
```
This error happens every 5 seconds.

I can't tell exactly when it started since it has been happening so much that it has caused older logs to be deleted (our log storage rolls based on storage space).

**Comment by boroskoyo** [comment]
We have found out the root cause and working on a fix to avoid log explosions for all our agents. I'll get back to you when it is solved

**Comment by probably-not** [comment]
Hey @serkan-ozal I see that you've closed this issue. Does this mean that the 502 errors have been fixed or that only the log explosion has been fixed?

**Comment by serkan-ozal** [comment]
Hi @probably-not, it has been closed automatically by Github when I merge the associated PR. @boroskoyo can give you more details about the issue

**Comment by boroskoyo** [comment]
Hi @probably-not, we have fixed log explosions in the agent. In case of 502 error, we haven't found anything more than one time connectivity problem. We will take further action if we encounter this problem again.

**Comment by probably-not** [comment]
Closing this as solved, there was on issue on the Sidekick side, an incorrect configuration.
