### ISSUE TITLE
VSCode Sidekick Plugin Tracepoint Events and Logpoint Event Does Not Refresh themselves Automatically

### ISSUE THREAD

**Issue by bcaglayan** [runsidekick/sidekick-agent-nodejs#4]
VSCode Sidekick Plugin tabs (SIDEKICK: TRACE EVENTS   &    SIDEKICK: LOG EVENTS) can be update themselves automatically when new tracepoint and logpoint events produced.

**Comment by probably-not** [comment]
Following here for updates on this specific issue, thanks @bcaglayan!

**Comment by boroskoyo** [comment]
@probably-not we have released a new version of our VS Code plugin. You can update yours via vscode marketplace

**Comment by probably-not** [comment]
Excellent, I'll check it out and update, thanks @boroskoyo

**Comment by probably-not** [comment]
Looks like it works! There's an issue in the encoding, I will open a separate one for that. Thanks!
